language: node_js
os:
- osx
node_js:
- '8'
install:
- travis_retry npm install -g esy@0.2.11
- travis_wait esy install
- ./test-fb.sh
script:
- travis_wait esy build
- esy b dune runtest
cache:
  timeout: 360
  directories:
  - "$HOME/.esy/"
