language: node_js

matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
    node_js: 8
    addons:
      apt:
        packages:
           - libxrandr-dev
           - libxinerama-dev
           - libxcursor-dev
           - libxi-dev
           - libegl1-mesa-dev
           - mesa-utils
  - os: osx # OSX 10.12
    node_js: 8


install:
- travis_retry npm install -g esy@0.2.11
- travis_wait esy install
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 6 # give xvfb some time to start
script:
- travis_wait 30 esy build
- glxinfo
- esy b dune runtest
cache:
  timeout: 360
  directories:
  - "$HOME/.esy/source-tarballs"
  - "$HOME/.esy/i"
